apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: debasnan-ingress-rule # name of my routing rule
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target:
spec:
  ingressClassName: nginx #we are using nginx ingress controller
  rules:
  - host: roche-ashu.delvex.io
    http:
      paths:
      - path: /debasnan
        pathType: Prefix
        backend:
          service:
            name: debasnan-dep1
            port:
              number: 80